// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stats_home_page.proto

package ateStatsHomePage

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//show the information of cluster
type ShowHomePageDataReq struct {
	ClusterId            string   `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowHomePageDataReq) Reset()         { *m = ShowHomePageDataReq{} }
func (m *ShowHomePageDataReq) String() string { return proto.CompactTextString(m) }
func (*ShowHomePageDataReq) ProtoMessage()    {}
func (*ShowHomePageDataReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_239cf65ed36bd756, []int{0}
}

func (m *ShowHomePageDataReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowHomePageDataReq.Unmarshal(m, b)
}
func (m *ShowHomePageDataReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowHomePageDataReq.Marshal(b, m, deterministic)
}
func (m *ShowHomePageDataReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowHomePageDataReq.Merge(m, src)
}
func (m *ShowHomePageDataReq) XXX_Size() int {
	return xxx_messageInfo_ShowHomePageDataReq.Size(m)
}
func (m *ShowHomePageDataReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowHomePageDataReq.DiscardUnknown(m)
}

var xxx_messageInfo_ShowHomePageDataReq proto.InternalMessageInfo

func (m *ShowHomePageDataReq) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

type ShowHomePageDataRsp struct {
	DomainIsNormal            uint32   `protobuf:"varint,1,opt,name=domain_is_normal,json=domainIsNormal,proto3" json:"domain_is_normal,omitempty"`
	DomainIsAbnormal          uint32   `protobuf:"varint,2,opt,name=domain_is_abnormal,json=domainIsAbnormal,proto3" json:"domain_is_abnormal,omitempty"`
	CurrentSessionTotalNumber uint64   `protobuf:"varint,3,opt,name=current_session_total_number,json=currentSessionTotalNumber,proto3" json:"current_session_total_number,omitempty"`
	NormalIpv6IpaddrNumber    uint32   `protobuf:"varint,4,opt,name=normal_ipv6_ipaddr_number,json=normalIpv6IpaddrNumber,proto3" json:"normal_ipv6_ipaddr_number,omitempty"`
	AbnormalIpv6IpaddrNumber  uint32   `protobuf:"varint,5,opt,name=abnormal_ipv6_ipaddr_number,json=abnormalIpv6IpaddrNumber,proto3" json:"abnormal_ipv6_ipaddr_number,omitempty"`
	NormalIpv4IpaddrNumber    uint32   `protobuf:"varint,6,opt,name=normal_ipv4_ipaddr_number,json=normalIpv4IpaddrNumber,proto3" json:"normal_ipv4_ipaddr_number,omitempty"`
	AbnormalIpv4IpaddrNumber  uint32   `protobuf:"varint,7,opt,name=abnormal_ipv4_ipaddr_number,json=abnormalIpv4IpaddrNumber,proto3" json:"abnormal_ipv4_ipaddr_number,omitempty"`
	NormalNodeNumber          uint32   `protobuf:"varint,8,opt,name=normal_node_number,json=normalNodeNumber,proto3" json:"normal_node_number,omitempty"`
	AbnormalNodeNumber        uint32   `protobuf:"varint,9,opt,name=abnormal_node_number,json=abnormalNodeNumber,proto3" json:"abnormal_node_number,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *ShowHomePageDataRsp) Reset()         { *m = ShowHomePageDataRsp{} }
func (m *ShowHomePageDataRsp) String() string { return proto.CompactTextString(m) }
func (*ShowHomePageDataRsp) ProtoMessage()    {}
func (*ShowHomePageDataRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_239cf65ed36bd756, []int{1}
}

func (m *ShowHomePageDataRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowHomePageDataRsp.Unmarshal(m, b)
}
func (m *ShowHomePageDataRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowHomePageDataRsp.Marshal(b, m, deterministic)
}
func (m *ShowHomePageDataRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowHomePageDataRsp.Merge(m, src)
}
func (m *ShowHomePageDataRsp) XXX_Size() int {
	return xxx_messageInfo_ShowHomePageDataRsp.Size(m)
}
func (m *ShowHomePageDataRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowHomePageDataRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ShowHomePageDataRsp proto.InternalMessageInfo

func (m *ShowHomePageDataRsp) GetDomainIsNormal() uint32 {
	if m != nil {
		return m.DomainIsNormal
	}
	return 0
}

func (m *ShowHomePageDataRsp) GetDomainIsAbnormal() uint32 {
	if m != nil {
		return m.DomainIsAbnormal
	}
	return 0
}

func (m *ShowHomePageDataRsp) GetCurrentSessionTotalNumber() uint64 {
	if m != nil {
		return m.CurrentSessionTotalNumber
	}
	return 0
}

func (m *ShowHomePageDataRsp) GetNormalIpv6IpaddrNumber() uint32 {
	if m != nil {
		return m.NormalIpv6IpaddrNumber
	}
	return 0
}

func (m *ShowHomePageDataRsp) GetAbnormalIpv6IpaddrNumber() uint32 {
	if m != nil {
		return m.AbnormalIpv6IpaddrNumber
	}
	return 0
}

func (m *ShowHomePageDataRsp) GetNormalIpv4IpaddrNumber() uint32 {
	if m != nil {
		return m.NormalIpv4IpaddrNumber
	}
	return 0
}

func (m *ShowHomePageDataRsp) GetAbnormalIpv4IpaddrNumber() uint32 {
	if m != nil {
		return m.AbnormalIpv4IpaddrNumber
	}
	return 0
}

func (m *ShowHomePageDataRsp) GetNormalNodeNumber() uint32 {
	if m != nil {
		return m.NormalNodeNumber
	}
	return 0
}

func (m *ShowHomePageDataRsp) GetAbnormalNodeNumber() uint32 {
	if m != nil {
		return m.AbnormalNodeNumber
	}
	return 0
}

//device flow stats
type ShowHomePageFlowDataReq struct {
	DeviceId             string   `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowHomePageFlowDataReq) Reset()         { *m = ShowHomePageFlowDataReq{} }
func (m *ShowHomePageFlowDataReq) String() string { return proto.CompactTextString(m) }
func (*ShowHomePageFlowDataReq) ProtoMessage()    {}
func (*ShowHomePageFlowDataReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_239cf65ed36bd756, []int{2}
}

func (m *ShowHomePageFlowDataReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowHomePageFlowDataReq.Unmarshal(m, b)
}
func (m *ShowHomePageFlowDataReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowHomePageFlowDataReq.Marshal(b, m, deterministic)
}
func (m *ShowHomePageFlowDataReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowHomePageFlowDataReq.Merge(m, src)
}
func (m *ShowHomePageFlowDataReq) XXX_Size() int {
	return xxx_messageInfo_ShowHomePageFlowDataReq.Size(m)
}
func (m *ShowHomePageFlowDataReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowHomePageFlowDataReq.DiscardUnknown(m)
}

var xxx_messageInfo_ShowHomePageFlowDataReq proto.InternalMessageInfo

func (m *ShowHomePageFlowDataReq) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

type DeviceFlowData struct {
	CurrentDeviceV4UpBytes   uint64   `protobuf:"varint,1,opt,name=current_device_v4_up_bytes,json=currentDeviceV4UpBytes,proto3" json:"current_device_v4_up_bytes,omitempty"`
	CurrentDeviceV4DownBytes uint64   `protobuf:"varint,2,opt,name=current_device_v4_down_bytes,json=currentDeviceV4DownBytes,proto3" json:"current_device_v4_down_bytes,omitempty"`
	CurrentDeviceV6UpBytes   uint64   `protobuf:"varint,3,opt,name=current_device_v6_up_bytes,json=currentDeviceV6UpBytes,proto3" json:"current_device_v6_up_bytes,omitempty"`
	CurrentDeviceV6DownBytes uint64   `protobuf:"varint,4,opt,name=current_device_v6_down_bytes,json=currentDeviceV6DownBytes,proto3" json:"current_device_v6_down_bytes,omitempty"`
	CurrentDeviceConnections uint32   `protobuf:"varint,5,opt,name=current_device_connections,json=currentDeviceConnections,proto3" json:"current_device_connections,omitempty"`
	Timestamp                uint64   `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *DeviceFlowData) Reset()         { *m = DeviceFlowData{} }
func (m *DeviceFlowData) String() string { return proto.CompactTextString(m) }
func (*DeviceFlowData) ProtoMessage()    {}
func (*DeviceFlowData) Descriptor() ([]byte, []int) {
	return fileDescriptor_239cf65ed36bd756, []int{3}
}

func (m *DeviceFlowData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceFlowData.Unmarshal(m, b)
}
func (m *DeviceFlowData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceFlowData.Marshal(b, m, deterministic)
}
func (m *DeviceFlowData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceFlowData.Merge(m, src)
}
func (m *DeviceFlowData) XXX_Size() int {
	return xxx_messageInfo_DeviceFlowData.Size(m)
}
func (m *DeviceFlowData) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceFlowData.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceFlowData proto.InternalMessageInfo

func (m *DeviceFlowData) GetCurrentDeviceV4UpBytes() uint64 {
	if m != nil {
		return m.CurrentDeviceV4UpBytes
	}
	return 0
}

func (m *DeviceFlowData) GetCurrentDeviceV4DownBytes() uint64 {
	if m != nil {
		return m.CurrentDeviceV4DownBytes
	}
	return 0
}

func (m *DeviceFlowData) GetCurrentDeviceV6UpBytes() uint64 {
	if m != nil {
		return m.CurrentDeviceV6UpBytes
	}
	return 0
}

func (m *DeviceFlowData) GetCurrentDeviceV6DownBytes() uint64 {
	if m != nil {
		return m.CurrentDeviceV6DownBytes
	}
	return 0
}

func (m *DeviceFlowData) GetCurrentDeviceConnections() uint32 {
	if m != nil {
		return m.CurrentDeviceConnections
	}
	return 0
}

func (m *DeviceFlowData) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type ShowHomePageFlowDataRsp struct {
	UpDowmFlow           []*DeviceFlowData `protobuf:"bytes,1,rep,name=up_dowm_flow,json=upDowmFlow,proto3" json:"up_dowm_flow,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ShowHomePageFlowDataRsp) Reset()         { *m = ShowHomePageFlowDataRsp{} }
func (m *ShowHomePageFlowDataRsp) String() string { return proto.CompactTextString(m) }
func (*ShowHomePageFlowDataRsp) ProtoMessage()    {}
func (*ShowHomePageFlowDataRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_239cf65ed36bd756, []int{4}
}

func (m *ShowHomePageFlowDataRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowHomePageFlowDataRsp.Unmarshal(m, b)
}
func (m *ShowHomePageFlowDataRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowHomePageFlowDataRsp.Marshal(b, m, deterministic)
}
func (m *ShowHomePageFlowDataRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowHomePageFlowDataRsp.Merge(m, src)
}
func (m *ShowHomePageFlowDataRsp) XXX_Size() int {
	return xxx_messageInfo_ShowHomePageFlowDataRsp.Size(m)
}
func (m *ShowHomePageFlowDataRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowHomePageFlowDataRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ShowHomePageFlowDataRsp proto.InternalMessageInfo

func (m *ShowHomePageFlowDataRsp) GetUpDowmFlow() []*DeviceFlowData {
	if m != nil {
		return m.UpDowmFlow
	}
	return nil
}

type ShowHomePageVisitorDataReq struct {
	ClusterId            string   `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowHomePageVisitorDataReq) Reset()         { *m = ShowHomePageVisitorDataReq{} }
func (m *ShowHomePageVisitorDataReq) String() string { return proto.CompactTextString(m) }
func (*ShowHomePageVisitorDataReq) ProtoMessage()    {}
func (*ShowHomePageVisitorDataReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_239cf65ed36bd756, []int{5}
}

func (m *ShowHomePageVisitorDataReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowHomePageVisitorDataReq.Unmarshal(m, b)
}
func (m *ShowHomePageVisitorDataReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowHomePageVisitorDataReq.Marshal(b, m, deterministic)
}
func (m *ShowHomePageVisitorDataReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowHomePageVisitorDataReq.Merge(m, src)
}
func (m *ShowHomePageVisitorDataReq) XXX_Size() int {
	return xxx_messageInfo_ShowHomePageVisitorDataReq.Size(m)
}
func (m *ShowHomePageVisitorDataReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowHomePageVisitorDataReq.DiscardUnknown(m)
}

var xxx_messageInfo_ShowHomePageVisitorDataReq proto.InternalMessageInfo

func (m *ShowHomePageVisitorDataReq) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

type VisitorData struct {
	HttpVisitorNumber    uint64   `protobuf:"varint,1,opt,name=http_visitor_number,json=httpVisitorNumber,proto3" json:"http_visitor_number,omitempty"`
	NeteVisitorNumber    uint64   `protobuf:"varint,2,opt,name=nete_visitor_number,json=neteVisitorNumber,proto3" json:"nete_visitor_number,omitempty"`
	Timestamp            uint64   `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VisitorData) Reset()         { *m = VisitorData{} }
func (m *VisitorData) String() string { return proto.CompactTextString(m) }
func (*VisitorData) ProtoMessage()    {}
func (*VisitorData) Descriptor() ([]byte, []int) {
	return fileDescriptor_239cf65ed36bd756, []int{6}
}

func (m *VisitorData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisitorData.Unmarshal(m, b)
}
func (m *VisitorData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisitorData.Marshal(b, m, deterministic)
}
func (m *VisitorData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisitorData.Merge(m, src)
}
func (m *VisitorData) XXX_Size() int {
	return xxx_messageInfo_VisitorData.Size(m)
}
func (m *VisitorData) XXX_DiscardUnknown() {
	xxx_messageInfo_VisitorData.DiscardUnknown(m)
}

var xxx_messageInfo_VisitorData proto.InternalMessageInfo

func (m *VisitorData) GetHttpVisitorNumber() uint64 {
	if m != nil {
		return m.HttpVisitorNumber
	}
	return 0
}

func (m *VisitorData) GetNeteVisitorNumber() uint64 {
	if m != nil {
		return m.NeteVisitorNumber
	}
	return 0
}

func (m *VisitorData) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type ShowHomePageVisitorDataRsp struct {
	AtsNeteVisitorNum    []*VisitorData `protobuf:"bytes,1,rep,name=ats_nete_visitor_num,json=atsNeteVisitorNum,proto3" json:"ats_nete_visitor_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ShowHomePageVisitorDataRsp) Reset()         { *m = ShowHomePageVisitorDataRsp{} }
func (m *ShowHomePageVisitorDataRsp) String() string { return proto.CompactTextString(m) }
func (*ShowHomePageVisitorDataRsp) ProtoMessage()    {}
func (*ShowHomePageVisitorDataRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_239cf65ed36bd756, []int{7}
}

func (m *ShowHomePageVisitorDataRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowHomePageVisitorDataRsp.Unmarshal(m, b)
}
func (m *ShowHomePageVisitorDataRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowHomePageVisitorDataRsp.Marshal(b, m, deterministic)
}
func (m *ShowHomePageVisitorDataRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowHomePageVisitorDataRsp.Merge(m, src)
}
func (m *ShowHomePageVisitorDataRsp) XXX_Size() int {
	return xxx_messageInfo_ShowHomePageVisitorDataRsp.Size(m)
}
func (m *ShowHomePageVisitorDataRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowHomePageVisitorDataRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ShowHomePageVisitorDataRsp proto.InternalMessageInfo

func (m *ShowHomePageVisitorDataRsp) GetAtsNeteVisitorNum() []*VisitorData {
	if m != nil {
		return m.AtsNeteVisitorNum
	}
	return nil
}

type ShowDomainVisitorDataReq struct {
	ClusterId            string   `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowDomainVisitorDataReq) Reset()         { *m = ShowDomainVisitorDataReq{} }
func (m *ShowDomainVisitorDataReq) String() string { return proto.CompactTextString(m) }
func (*ShowDomainVisitorDataReq) ProtoMessage()    {}
func (*ShowDomainVisitorDataReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_239cf65ed36bd756, []int{8}
}

func (m *ShowDomainVisitorDataReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowDomainVisitorDataReq.Unmarshal(m, b)
}
func (m *ShowDomainVisitorDataReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowDomainVisitorDataReq.Marshal(b, m, deterministic)
}
func (m *ShowDomainVisitorDataReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowDomainVisitorDataReq.Merge(m, src)
}
func (m *ShowDomainVisitorDataReq) XXX_Size() int {
	return xxx_messageInfo_ShowDomainVisitorDataReq.Size(m)
}
func (m *ShowDomainVisitorDataReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowDomainVisitorDataReq.DiscardUnknown(m)
}

var xxx_messageInfo_ShowDomainVisitorDataReq proto.InternalMessageInfo

func (m *ShowDomainVisitorDataReq) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

type VisitDomainNum struct {
	VisitDomainNum       uint64   `protobuf:"varint,1,opt,name=visit_domain_num,json=visitDomainNum,proto3" json:"visit_domain_num,omitempty"`
	Timestamp            uint64   `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VisitDomainNum) Reset()         { *m = VisitDomainNum{} }
func (m *VisitDomainNum) String() string { return proto.CompactTextString(m) }
func (*VisitDomainNum) ProtoMessage()    {}
func (*VisitDomainNum) Descriptor() ([]byte, []int) {
	return fileDescriptor_239cf65ed36bd756, []int{9}
}

func (m *VisitDomainNum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VisitDomainNum.Unmarshal(m, b)
}
func (m *VisitDomainNum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VisitDomainNum.Marshal(b, m, deterministic)
}
func (m *VisitDomainNum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VisitDomainNum.Merge(m, src)
}
func (m *VisitDomainNum) XXX_Size() int {
	return xxx_messageInfo_VisitDomainNum.Size(m)
}
func (m *VisitDomainNum) XXX_DiscardUnknown() {
	xxx_messageInfo_VisitDomainNum.DiscardUnknown(m)
}

var xxx_messageInfo_VisitDomainNum proto.InternalMessageInfo

func (m *VisitDomainNum) GetVisitDomainNum() uint64 {
	if m != nil {
		return m.VisitDomainNum
	}
	return 0
}

func (m *VisitDomainNum) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type DomainVisitor struct {
	VisitHostNumber      []*VisitDomainNum `protobuf:"bytes,1,rep,name=visit_host_number,json=visitHostNumber,proto3" json:"visit_host_number,omitempty"`
	MemberDomain         string            `protobuf:"bytes,2,opt,name=member_domain,json=memberDomain,proto3" json:"member_domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DomainVisitor) Reset()         { *m = DomainVisitor{} }
func (m *DomainVisitor) String() string { return proto.CompactTextString(m) }
func (*DomainVisitor) ProtoMessage()    {}
func (*DomainVisitor) Descriptor() ([]byte, []int) {
	return fileDescriptor_239cf65ed36bd756, []int{10}
}

func (m *DomainVisitor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DomainVisitor.Unmarshal(m, b)
}
func (m *DomainVisitor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DomainVisitor.Marshal(b, m, deterministic)
}
func (m *DomainVisitor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DomainVisitor.Merge(m, src)
}
func (m *DomainVisitor) XXX_Size() int {
	return xxx_messageInfo_DomainVisitor.Size(m)
}
func (m *DomainVisitor) XXX_DiscardUnknown() {
	xxx_messageInfo_DomainVisitor.DiscardUnknown(m)
}

var xxx_messageInfo_DomainVisitor proto.InternalMessageInfo

func (m *DomainVisitor) GetVisitHostNumber() []*VisitDomainNum {
	if m != nil {
		return m.VisitHostNumber
	}
	return nil
}

func (m *DomainVisitor) GetMemberDomain() string {
	if m != nil {
		return m.MemberDomain
	}
	return ""
}

type ShowDomainVisitorDataRsp struct {
	DomainVisitNum       []*DomainVisitor `protobuf:"bytes,1,rep,name=domain_visit_num,json=domainVisitNum,proto3" json:"domain_visit_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ShowDomainVisitorDataRsp) Reset()         { *m = ShowDomainVisitorDataRsp{} }
func (m *ShowDomainVisitorDataRsp) String() string { return proto.CompactTextString(m) }
func (*ShowDomainVisitorDataRsp) ProtoMessage()    {}
func (*ShowDomainVisitorDataRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_239cf65ed36bd756, []int{11}
}

func (m *ShowDomainVisitorDataRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowDomainVisitorDataRsp.Unmarshal(m, b)
}
func (m *ShowDomainVisitorDataRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowDomainVisitorDataRsp.Marshal(b, m, deterministic)
}
func (m *ShowDomainVisitorDataRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowDomainVisitorDataRsp.Merge(m, src)
}
func (m *ShowDomainVisitorDataRsp) XXX_Size() int {
	return xxx_messageInfo_ShowDomainVisitorDataRsp.Size(m)
}
func (m *ShowDomainVisitorDataRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowDomainVisitorDataRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ShowDomainVisitorDataRsp proto.InternalMessageInfo

func (m *ShowDomainVisitorDataRsp) GetDomainVisitNum() []*DomainVisitor {
	if m != nil {
		return m.DomainVisitNum
	}
	return nil
}

func init() {
	proto.RegisterType((*ShowHomePageDataReq)(nil), "ateStatsHomePage.ShowHomePageDataReq")
	proto.RegisterType((*ShowHomePageDataRsp)(nil), "ateStatsHomePage.ShowHomePageDataRsp")
	proto.RegisterType((*ShowHomePageFlowDataReq)(nil), "ateStatsHomePage.ShowHomePageFlowDataReq")
	proto.RegisterType((*DeviceFlowData)(nil), "ateStatsHomePage.DeviceFlowData")
	proto.RegisterType((*ShowHomePageFlowDataRsp)(nil), "ateStatsHomePage.ShowHomePageFlowDataRsp")
	proto.RegisterType((*ShowHomePageVisitorDataReq)(nil), "ateStatsHomePage.ShowHomePageVisitorDataReq")
	proto.RegisterType((*VisitorData)(nil), "ateStatsHomePage.VisitorData")
	proto.RegisterType((*ShowHomePageVisitorDataRsp)(nil), "ateStatsHomePage.ShowHomePageVisitorDataRsp")
	proto.RegisterType((*ShowDomainVisitorDataReq)(nil), "ateStatsHomePage.ShowDomainVisitorDataReq")
	proto.RegisterType((*VisitDomainNum)(nil), "ateStatsHomePage.VisitDomainNum")
	proto.RegisterType((*DomainVisitor)(nil), "ateStatsHomePage.DomainVisitor")
	proto.RegisterType((*ShowDomainVisitorDataRsp)(nil), "ateStatsHomePage.ShowDomainVisitorDataRsp")
}

func init() { proto.RegisterFile("stats_home_page.proto", fileDescriptor_239cf65ed36bd756) }

var fileDescriptor_239cf65ed36bd756 = []byte{
	// 777 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0x6d, 0x6b, 0xdb, 0x48,
	0x10, 0x3e, 0xbf, 0x5c, 0x2e, 0x9e, 0x24, 0x3e, 0x7b, 0xf3, 0xe6, 0x38, 0x09, 0x67, 0x74, 0x1c,
	0xf8, 0x8e, 0x60, 0x8e, 0xd4, 0x18, 0xd2, 0x57, 0x92, 0x9a, 0x12, 0x43, 0x31, 0x45, 0x69, 0x43,
	0xbf, 0x94, 0x45, 0xb6, 0xb6, 0xb1, 0xc0, 0xd2, 0x6e, 0xb4, 0x2b, 0x9b, 0x7e, 0xcd, 0xd7, 0xfe,
	0xbb, 0xfe, 0x86, 0xfe, 0x90, 0xa2, 0xdd, 0x55, 0xf4, 0x62, 0xd9, 0x38, 0xdf, 0xa2, 0x99, 0xe7,
	0x99, 0x67, 0x3c, 0xf3, 0x68, 0x14, 0xd8, 0xe7, 0xc2, 0x12, 0x1c, 0x4f, 0xa8, 0x4b, 0x30, 0xb3,
	0xee, 0x48, 0x87, 0xf9, 0x54, 0x50, 0x54, 0xb3, 0x04, 0xb9, 0x09, 0x33, 0xd7, 0xd4, 0x25, 0x1f,
	0xac, 0x3b, 0x62, 0x74, 0x61, 0xf7, 0x66, 0x42, 0xe7, 0xd1, 0x73, 0xdf, 0x12, 0x96, 0x49, 0xee,
	0xd1, 0x29, 0xc0, 0x78, 0x1a, 0x70, 0x41, 0x7c, 0xec, 0xd8, 0x8d, 0x42, 0xab, 0xd0, 0xae, 0x98,
	0x15, 0x1d, 0x19, 0xd8, 0xc6, 0x43, 0x39, 0x87, 0xc6, 0x19, 0x6a, 0x43, 0xcd, 0xa6, 0xae, 0xe5,
	0x78, 0xd8, 0xe1, 0xd8, 0xa3, 0xbe, 0x6b, 0x4d, 0x25, 0x79, 0xc7, 0xac, 0xaa, 0xf8, 0x80, 0x0f,
	0x65, 0x14, 0x9d, 0x01, 0x8a, 0x91, 0xd6, 0x48, 0x63, 0x8b, 0x12, 0x5b, 0x8b, 0xb0, 0x97, 0x3a,
	0x8e, 0xde, 0xc0, 0xc9, 0x38, 0xf0, 0x7d, 0xe2, 0x09, 0xcc, 0x09, 0xe7, 0x0e, 0xf5, 0xb0, 0xa0,
	0xc2, 0x9a, 0x62, 0x2f, 0x70, 0x47, 0xc4, 0x6f, 0x94, 0x5a, 0x85, 0x76, 0xd9, 0x3c, 0xd2, 0x98,
	0x1b, 0x05, 0xf9, 0x18, 0x22, 0x86, 0x12, 0x80, 0x2e, 0xe0, 0x48, 0x95, 0xc2, 0x0e, 0x9b, 0xf5,
	0xb0, 0xc3, 0x2c, 0xdb, 0xf6, 0x23, 0x76, 0x59, 0xaa, 0x1e, 0x28, 0xc0, 0x80, 0xcd, 0x7a, 0x03,
	0x99, 0xd6, 0xd4, 0x57, 0x70, 0x1c, 0xf5, 0x97, 0x47, 0xfe, 0x5d, 0x92, 0x1b, 0x11, 0x64, 0x81,
	0x9e, 0x52, 0xee, 0x66, 0xc8, 0x1b, 0x19, 0xe5, 0xee, 0x2a, 0xe5, 0x2c, 0xf9, 0x8f, 0x05, 0xe5,
	0x34, 0xfd, 0x0c, 0x90, 0x26, 0x7b, 0xd4, 0x26, 0x11, 0x6b, 0x53, 0x8d, 0x58, 0x65, 0x86, 0xd4,
	0x26, 0x1a, 0xfd, 0x3f, 0xec, 0x3d, 0x8a, 0x25, 0xf1, 0x15, 0x89, 0x47, 0x51, 0x2e, 0x66, 0x18,
	0x3d, 0x38, 0x4c, 0x7a, 0xe0, 0xdd, 0x94, 0xce, 0x23, 0xfb, 0x1c, 0x43, 0xc5, 0x26, 0x33, 0x67,
	0x4c, 0x42, 0xf7, 0x14, 0xa5, 0x7b, 0x36, 0x55, 0x60, 0x60, 0x1b, 0x3f, 0x8b, 0x50, 0xed, 0xcb,
	0x87, 0x88, 0x82, 0x9e, 0x43, 0x33, 0xda, 0xaf, 0xe6, 0xcd, 0xba, 0x38, 0x60, 0x78, 0xf4, 0x4d,
	0x10, 0x2e, 0x1d, 0x54, 0x36, 0x0f, 0x34, 0x42, 0x51, 0x6f, 0xbb, 0x9f, 0xd8, 0x55, 0x98, 0x45,
	0xaf, 0x63, 0x6f, 0xc4, 0x5c, 0x9b, 0xce, 0x3d, 0xcd, 0x2e, 0x4a, 0x76, 0x23, 0xc3, 0xee, 0xd3,
	0xb9, 0xa7, 0xf8, 0x39, 0xda, 0xbd, 0x58, 0xbb, 0x94, 0xa7, 0xdd, 0x5b, 0xa1, 0xdd, 0x4b, 0x6a,
	0x97, 0xf3, 0xb4, 0x7b, 0xb1, 0xf6, 0xcb, 0x05, 0xed, 0x31, 0xf5, 0x3c, 0x32, 0x16, 0x0e, 0xf5,
	0x78, 0x64, 0xad, 0x14, 0xfb, 0x6d, 0x9c, 0x47, 0x27, 0x50, 0x11, 0x8e, 0x4b, 0xb8, 0xb0, 0x5c,
	0x26, 0xad, 0x54, 0x36, 0xe3, 0x80, 0xf1, 0x65, 0xc9, 0x7a, 0x38, 0x43, 0x57, 0xb0, 0x1d, 0xb0,
	0xb0, 0x4f, 0x17, 0x7f, 0x9d, 0xd2, 0x79, 0xa3, 0xd0, 0x2a, 0xb5, 0xb7, 0xce, 0x5b, 0x9d, 0xec,
	0x75, 0xe8, 0xa4, 0xd7, 0x64, 0x42, 0xc0, 0xfa, 0x74, 0xee, 0x86, 0xcf, 0xc6, 0x0b, 0x68, 0x26,
	0xcb, 0xdf, 0x3a, 0xdc, 0x11, 0xd4, 0x5f, 0xf3, 0x7e, 0x7c, 0x2f, 0xc0, 0x56, 0x82, 0x81, 0x3a,
	0xb0, 0x3b, 0x11, 0x82, 0xe1, 0x99, 0x8a, 0x45, 0xde, 0x53, 0x8b, 0xaf, 0x87, 0x29, 0x8d, 0xd6,
	0x66, 0xed, 0xc0, 0xae, 0x47, 0x04, 0xc9, 0xe2, 0xd5, 0xaa, 0xeb, 0x61, 0x2a, 0x8d, 0x4f, 0x4d,
	0xaa, 0x94, 0x9d, 0xd4, 0x74, 0xf9, 0x4f, 0xe1, 0x0c, 0x0d, 0x61, 0x2f, 0x3c, 0xa5, 0x59, 0x3d,
	0x3d, 0xb4, 0xd3, 0xc5, 0xa1, 0x25, 0xf9, 0x75, 0x4b, 0xf0, 0x61, 0xaa, 0x1d, 0xe3, 0x02, 0x1a,
	0xa1, 0x5a, 0x5f, 0xde, 0xb8, 0xa7, 0x8d, 0xed, 0x33, 0x54, 0x25, 0x41, 0x71, 0x87, 0x81, 0x1b,
	0x1e, 0x5c, 0xd9, 0x13, 0xd6, 0xc7, 0x54, 0x35, 0x16, 0xfe, 0xbe, 0xea, 0x2c, 0x8d, 0x4c, 0x8d,
	0xa0, 0x98, 0x1d, 0xc1, 0x43, 0x01, 0x76, 0x52, 0x1d, 0xa1, 0xf7, 0x50, 0x57, 0x95, 0x27, 0x94,
	0x8b, 0x78, 0x21, 0x4b, 0x8c, 0x92, 0x6e, 0xcb, 0xfc, 0x53, 0x52, 0xaf, 0x29, 0x17, 0x7a, 0x01,
	0x7f, 0xc3, 0x8e, 0x4b, 0xc2, 0xbf, 0x74, 0xa3, 0xfa, 0x28, 0x6c, 0xab, 0xa0, 0x22, 0x1a, 0x64,
	0xd9, 0x64, 0x38, 0x43, 0x83, 0xc7, 0x2f, 0x8b, 0xea, 0x2a, 0xde, 0xc0, 0x5f, 0x39, 0xb6, 0x4d,
	0x56, 0x88, 0x3e, 0x3d, 0xf2, 0x71, 0x18, 0xb8, 0xe7, 0x3f, 0x4a, 0x50, 0xbb, 0xcc, 0x50, 0xd0,
	0x08, 0x6a, 0x3c, 0xf3, 0x41, 0x43, 0xff, 0x2c, 0x56, 0xce, 0xf9, 0x56, 0x36, 0xd7, 0x81, 0x71,
	0x66, 0xfc, 0x86, 0x3c, 0xd8, 0xe3, 0x39, 0x6f, 0x24, 0xfa, 0x77, 0x75, 0x81, 0xc4, 0x61, 0x6d,
	0xae, 0x0b, 0x95, 0x7a, 0x73, 0x38, 0xe4, 0xf9, 0xbe, 0x46, 0x67, 0xab, 0xeb, 0xa4, 0x6d, 0xd9,
	0x7c, 0x02, 0x5a, 0x0a, 0xdf, 0xc3, 0x3e, 0xcf, 0x5b, 0x24, 0xfa, 0x2f, 0xbf, 0x50, 0xde, 0xbb,
	0xd0, 0x5c, 0x1b, 0x1b, 0x4a, 0x8e, 0x36, 0xe4, 0x3f, 0x38, 0xcf, 0x7e, 0x05, 0x00, 0x00, 0xff,
	0xff, 0xde, 0xcf, 0xed, 0x74, 0xf9, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AteStatsHomePageClient is the client API for AteStatsHomePage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AteStatsHomePageClient interface {
	//homepage stats
	ShowHomePageData(ctx context.Context, in *ShowHomePageDataReq, opts ...grpc.CallOption) (*ShowHomePageDataRsp, error)
	ShowHomePageFlowData(ctx context.Context, in *ShowHomePageFlowDataReq, opts ...grpc.CallOption) (*ShowHomePageFlowDataRsp, error)
	ShowHomePageVisitorData(ctx context.Context, in *ShowHomePageVisitorDataReq, opts ...grpc.CallOption) (*ShowHomePageVisitorDataRsp, error)
	ShowDomainVisitorData(ctx context.Context, in *ShowDomainVisitorDataReq, opts ...grpc.CallOption) (*ShowDomainVisitorDataRsp, error)
}

type ateStatsHomePageClient struct {
	cc *grpc.ClientConn
}

func NewAteStatsHomePageClient(cc *grpc.ClientConn) AteStatsHomePageClient {
	return &ateStatsHomePageClient{cc}
}

func (c *ateStatsHomePageClient) ShowHomePageData(ctx context.Context, in *ShowHomePageDataReq, opts ...grpc.CallOption) (*ShowHomePageDataRsp, error) {
	out := new(ShowHomePageDataRsp)
	err := c.cc.Invoke(ctx, "/ateStatsHomePage.AteStatsHomePage/showHomePageData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ateStatsHomePageClient) ShowHomePageFlowData(ctx context.Context, in *ShowHomePageFlowDataReq, opts ...grpc.CallOption) (*ShowHomePageFlowDataRsp, error) {
	out := new(ShowHomePageFlowDataRsp)
	err := c.cc.Invoke(ctx, "/ateStatsHomePage.AteStatsHomePage/showHomePageFlowData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ateStatsHomePageClient) ShowHomePageVisitorData(ctx context.Context, in *ShowHomePageVisitorDataReq, opts ...grpc.CallOption) (*ShowHomePageVisitorDataRsp, error) {
	out := new(ShowHomePageVisitorDataRsp)
	err := c.cc.Invoke(ctx, "/ateStatsHomePage.AteStatsHomePage/showHomePageVisitorData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ateStatsHomePageClient) ShowDomainVisitorData(ctx context.Context, in *ShowDomainVisitorDataReq, opts ...grpc.CallOption) (*ShowDomainVisitorDataRsp, error) {
	out := new(ShowDomainVisitorDataRsp)
	err := c.cc.Invoke(ctx, "/ateStatsHomePage.AteStatsHomePage/showDomainVisitorData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AteStatsHomePageServer is the server API for AteStatsHomePage service.
type AteStatsHomePageServer interface {
	//homepage stats
	ShowHomePageData(context.Context, *ShowHomePageDataReq) (*ShowHomePageDataRsp, error)
	ShowHomePageFlowData(context.Context, *ShowHomePageFlowDataReq) (*ShowHomePageFlowDataRsp, error)
	ShowHomePageVisitorData(context.Context, *ShowHomePageVisitorDataReq) (*ShowHomePageVisitorDataRsp, error)
	ShowDomainVisitorData(context.Context, *ShowDomainVisitorDataReq) (*ShowDomainVisitorDataRsp, error)
}

// UnimplementedAteStatsHomePageServer can be embedded to have forward compatible implementations.
type UnimplementedAteStatsHomePageServer struct {
}

func (*UnimplementedAteStatsHomePageServer) ShowHomePageData(ctx context.Context, req *ShowHomePageDataReq) (*ShowHomePageDataRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowHomePageData not implemented")
}
func (*UnimplementedAteStatsHomePageServer) ShowHomePageFlowData(ctx context.Context, req *ShowHomePageFlowDataReq) (*ShowHomePageFlowDataRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowHomePageFlowData not implemented")
}
func (*UnimplementedAteStatsHomePageServer) ShowHomePageVisitorData(ctx context.Context, req *ShowHomePageVisitorDataReq) (*ShowHomePageVisitorDataRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowHomePageVisitorData not implemented")
}
func (*UnimplementedAteStatsHomePageServer) ShowDomainVisitorData(ctx context.Context, req *ShowDomainVisitorDataReq) (*ShowDomainVisitorDataRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShowDomainVisitorData not implemented")
}

func RegisterAteStatsHomePageServer(s *grpc.Server, srv AteStatsHomePageServer) {
	s.RegisterService(&_AteStatsHomePage_serviceDesc, srv)
}

func _AteStatsHomePage_ShowHomePageData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowHomePageDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AteStatsHomePageServer).ShowHomePageData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ateStatsHomePage.AteStatsHomePage/ShowHomePageData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AteStatsHomePageServer).ShowHomePageData(ctx, req.(*ShowHomePageDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AteStatsHomePage_ShowHomePageFlowData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowHomePageFlowDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AteStatsHomePageServer).ShowHomePageFlowData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ateStatsHomePage.AteStatsHomePage/ShowHomePageFlowData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AteStatsHomePageServer).ShowHomePageFlowData(ctx, req.(*ShowHomePageFlowDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AteStatsHomePage_ShowHomePageVisitorData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowHomePageVisitorDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AteStatsHomePageServer).ShowHomePageVisitorData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ateStatsHomePage.AteStatsHomePage/ShowHomePageVisitorData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AteStatsHomePageServer).ShowHomePageVisitorData(ctx, req.(*ShowHomePageVisitorDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AteStatsHomePage_ShowDomainVisitorData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowDomainVisitorDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AteStatsHomePageServer).ShowDomainVisitorData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ateStatsHomePage.AteStatsHomePage/ShowDomainVisitorData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AteStatsHomePageServer).ShowDomainVisitorData(ctx, req.(*ShowDomainVisitorDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AteStatsHomePage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ateStatsHomePage.AteStatsHomePage",
	HandlerType: (*AteStatsHomePageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "showHomePageData",
			Handler:    _AteStatsHomePage_ShowHomePageData_Handler,
		},
		{
			MethodName: "showHomePageFlowData",
			Handler:    _AteStatsHomePage_ShowHomePageFlowData_Handler,
		},
		{
			MethodName: "showHomePageVisitorData",
			Handler:    _AteStatsHomePage_ShowHomePageVisitorData_Handler,
		},
		{
			MethodName: "showDomainVisitorData",
			Handler:    _AteStatsHomePage_ShowDomainVisitorData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stats_home_page.proto",
}
